version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./backend:/home/app

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3001
    depends_on:
      - backend