FROM node:18-alpine

RUN apk add --no-cache ffmpeg

WORKDIR /home/app

# Copy the entire backend directory
COPY . .

# Install dependencies
RUN npm install

# Verify installation of express
RUN npm list express

EXPOSE 3001

CMD ["node", "index.js"]